### ISSUE TITLE
the `py.test workaround hides legitimate mistakes

### ISSUE THREAD

**Issue by RonnyPfannschmidt** [pytest-dev/apipkg#10]
c9b997713cb77d2c1334acb7847ee6b24e3261b2 introduced returning None on missing aliasmodules unconditionally
this does hide actual errors

**Comment by SimonBiggs** [comment]
Thank you for this bug report. By using apipkg >=1.0,<=1.2 error messages for missing imports are given to the user as an `ImportError` instead of `None not callable` or something of the like.

Given that Python 3.4 has now reached its end of life (https://www.python.org/dev/peps/pep-0429/#id4) I am of the opinion that this workaround should now be reverted.
